### PR TITLE
bug/ missing strong random number source

### PR DESCRIPTION
**Pull request by JGiter**

### CODE REVIEW

**Review by nichonien — APPROVED** [review]
The warning is gone for the tests in `claims` and `did-registry` package. Thanks @JGiter !

**Review by jrhender — APPROVED** [review]

**Comment by JGiter** [comment]
The commit footer is too long for this rule https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#footer-max-line-length. Should we change shorten description like `ethers/lib/utils is not external module` or override commitlint rule?

**Comment by jrhender** [comment]
> @jrhender The commit footer is too long for this rule https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#footer-max-line-length. Should we change shorten description like `ethers/lib/utils is not external module` or override commitlint rule?

ah okay, good point. Sure, please make it short enough to fit into the footer

**Review by jrhender — APPROVED** [review]
Perfect, thanks @JGiter !

**Pull request merged**
