### PR TITLE
Fix/edr 15/update doc offerable identity

### PR DESCRIPTION
**Pull request by jrhender**
### Summary

|             |   |
|-------------|---|
| Description | Core of change is that getting proxyIdentity package tests to run during CI and pass with ethers v5   |
| Jira issue  | EDR-14, EDR-15   |

#### Type of request

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

### List of Features

- [x] Run offerable-identity tests as part of "npm run test"
- [x] Add root package-lock.json
- [x] Fix params issue in offerableIdentityOperator
- [x] `validity` parameter is not included in `revokeAttribute` transaction sent by `OfferableIdentityOperator`
- [x] `EthereumDIDRegistry` method to invoke will be identified by its name instead of resolving from updated DID attribute
- [x] Ensure that offerable-idenity tests are passing in CI (might need to add contract build)

### CODE REVIEW

**Review by knzeng-e — DISMISSED** [review]
Looks good to me, Thank you @jrhender !

**Review by JGiter — COMMENTED** [review]
I suggest use same npm script names as in other packages, which are `test` and `test-rpc`. I included this change  in proposed commits
Also these commits fixes two flaws, which I've added to PR description

**Comment by jrhender** [comment]
@JGiter Why this change?
>  EthereumDIDRegistry method to invoke will be identified by its name instead of resolving from updated DID attribute

**Comment by JGiter** [comment]
> @JGiter Why this change?
> 
> > EthereumDIDRegistry method to invoke will be identified by its name instead of resolving from updated DID attribute

`OfferableIdentityOperator._sendTransaction` doesn't determine `revokeAttribute` method (https://github.com/energywebfoundation/ew-did-registry/blob/bcba5f5344eddf8b05dc5f500c026f20f14c860c/packages/proxyIdentity/src/offerableIdentityOperator.ts#L89). It can be detected by comparing validity with 0 or `revokeAttribute` can be overridden, but for me the most straightforward way is explicitly set method name. Initial approach of passing in `Function` to `_sendTransaction` leads to unnecessary  complications

**Pull request merged**
