### PR TITLE
task/remove cluster specific methods

### PR DESCRIPTION
**Pull request by JGiter**
### Summary

|             |   |
|-------------|---|
| Description | `DidStore` will provide only `get` and `save`. Methods for pinning and checking of pinning status removed assuming that pinning is default behavior for Infura and cluster. Store can be initialized with IPFS API url regardless whether it comes from cluster or Infura. Tests includes connection with gateway. Credentials for gateway should be set in .env of did-ipfs-store/test
 |

### CODE REVIEW

**Comment by jrhender** [comment]
@JGiter , from the CI, it seems there is a failing test here:
```
  1) [DID-STORE-PACKAGE]
       [LOCAL CLUSTER]
         cluster content should be resolved by Infura and cluster CIDs:
     Error: Content with identifier QmXeopgnwFcXXZ331jXybk2LQiHPXkMUHFmexckJHYxH43 was not found in DID Store : Timeout 30000 msec expired
      at DidStore.<anonymous> (src/didStore.ts:64:15)
```
Do you know what is happening here?

**Comment by JGiter** [comment]
@jrhender Locally this test passes. I suspect that gateway can't be used in Github action. I asked devops to create dedicate gateway

**Comment by jrhender** [comment]
@JGiter Please try https://ew-did-store-testing.infura-ipfs.io/

**Comment by JGiter** [comment]
> @JGiter Please try https://ew-did-store-testing.infura-ipfs.io/

Thanks. This works

**Review by jrhender — APPROVED** [review]
Looks good to me, thanks @JGiter

**Pull request merged**
