### PR TITLE
fix: pin dependencies

### PR DESCRIPTION
**Pull request by nichonien**

### CODE REVIEW

**Review by JGiter — COMMENTED** [review]
Are these dependencies break build? This pinning looks dangerous to me. We can miss bugfixes

**Comment by nichonien** [comment]
> Are these dependencies break build? This pinning looks dangerous to me. We can miss bugfixes

I didn't get you @JGiter, can you explain why it doesn't look right to you. It sometimes does break the builds in the importing repos, so we are pining every dependency to be safe. It will increase the efforts to update these dependency every time but it would be safe.

**Comment by JGiter** [comment]
If I understand correctly pinning makes dependabot ignore looking for updates and fixes. Do you propose to update dependencies manually every time when some changes are made in ew-did-registry?

**Comment by nichonien** [comment]
`ew-did-registry` is a "dual browser/node.js" library and it is not recommended to pin dependencies in such repos - https://docs.renovatebot.com/dependency-pinning/#so-whats-best.

**Pull request closed without merging**
