### PR TITLE
chore: update eslint config

### PR DESCRIPTION
**Pull request by Harasz**
### Summary

|             |   |
|-------------|---|
| Description |  Update eslint config |
| Jira issue  |   |

#### Type of request

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

### List of Features

- Update EWF eslint config

### CODE REVIEW

**Review by JGiter — DISMISSED** [review]

**Comment by Harasz** [comment]
@JGiter @nichonien @jrhender Any idea why CI is failing?

**Comment by JGiter** [comment]
> @JGiter @nichonien @jrhender Any idea why CI is failing?

`@zondax/filecoin-signing-tools` should be installed from @zondax/filecoin-signing-tools instead from github (don't know why), but it was updated in package-lock

**Comment by Harasz** [comment]
Okay I see. My `npm install` overwritten it. We should make it more stable

**Comment by nichonien** [comment]
> Okay I see. My `npm install` overwritten it. We should make it more stable

That's actually wrong from `@zondax/filecoin-signing-tools`, I faced this multiple times, I had to revert the changes specific to it. It automatically updates it to install from `github`.

**Review by nichonien — APPROVED** [review]

**Review by JGiter — APPROVED** [review]

**Pull request merged**
