### PR TITLE
feat: validate duplicate service endpoint addition

### PR DESCRIPTION
**Pull request by nichonien**
### Summary

|             |   |
|-------------|---|
| Description | Add validation check for duplicate service endpoint addition in services for a DID  |
| Jira issue  |  https://energyweb.atlassian.net/browse/SWTCH-1822  |

### CODE REVIEW

**Review by JGiter — COMMENTED** [review]
Are you sure this will prevent duplication? For me it looks like this change prevents updating of existing service. I think duplication is caused by reading of logs

**Comment by nichonien** [comment]
> Are you sure this will prevent duplication? For me it looks like this change prevents updating of existing service. I think duplication is caused by reading of logs

For every DID Document update we only add new service endpoint for a credential. So this would block any change for which the service endpoint exists, be it new addition or updation.

**Review by jrhender — COMMENTED** [review]
The code change looks good to me.
However, I recommend that a test be added for this duplicate service case. I think a test added to this file would do the trick: https://github.com/energywebfoundation/ew-did-registry/blob/development/packages/did-ethr-resolver/test/did-operator.test.ts

**Review by JGiter — COMMENTED** [review]
Will service be duplicated if someone updates it not by ew-did-registy, but directly calling EthrDidRegistry?

**Comment by nichonien** [comment]
> Will service be duplicated if someone updates it not by ew-did-registy, but directly calling EthrDidRegistry?

Yeah, the only way to prevent this is to update the didRegistry contract which isn't feasible.

**Comment by nichonien** [comment]
> > Yeah, the only way to prevent this is to update the didRegistry contract which isn't feasible.
> 
> Do you think it is correct behavior of `Resolver.read(did)`, when it is returns duplicate services?

Aah, that's a nice point. Although IMO I would keep `Resolver.read(did)` as it is since the addition of duplicate check for service endpoint will prevent future occurrences and the resolver remains generic and returns all services without any filter.

**Review by jrhender — APPROVED** [review]

**Pull request merged**
